### PR TITLE
add Norway to the list

### PR DESCRIPTION
**Pull request by bjarneo**

### CODE REVIEW

**Comment by yireo** [comment]
Whoops. Did we forget Norway?!? I'm not sure why, but thanks for the fix.

**Comment by yireo** [comment]
Merged.

**Comment by hostep** [comment]
Hmm, is this correct? Since Norway isn't a member state of the European Union and you previously only had countries from the European Union in the list?

**Comment by bjarneo** [comment]
Oh, I thought EU in Europe. If it's the union it is not correct. Norway just have a EFTA agreement.

**Comment by hostep** [comment]
Hmm, never heard about that EFTA agreement.
I just checked it out and apparently it has got nothing to do with the [EU VAT area](https://en.wikipedia.org/wiki/European_Union_value_added_tax#EU_VAT_area). See this table on the wikipedia article: https://en.wikipedia.org/wiki/European_Free_Trade_Association#European_Union

@yireo: I'll leave it up to you to decide if you want to add non-EU country taxes to your github project.

**Comment by yireo** [comment]
@hostep @bjarneo thanks for the input - it is very useful. I guess I wanted to merge this too quickly. The purpose of this repo is to allow EU shop owners to quickly setup their stores with EU tax rates. The tax rates are useless for - let's say a US shop owner - because no VAT is charged when US customers buy from the EU. So hence, only EU countries should be lists in this repo. I read some papers on EU VAT, EFTA and Norway, but can't find any evidence that EU VAT rules apply here. So I will apply a new commit to remove Norway once again :(

**Pull request merged**
